### ISSUE TITLE
[Epic] Init the API and Database

### ISSUE THREAD

**Issue by philip-gai** [slashkudos/kudos-api#1]
- [x] #3 **AWS**
- [x] #5 **Node+Typescript+GraphQL**
- [x] #6 **Dynamo (Document) because of price**
- [x] #4 **AWS AppSync + Dynamo**
- [x] #7
- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #8
